name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            cd backend
            git pull origin main
            
            rm -rf .env
            touch .env
            echo NODE_ENV=production >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            echo DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} >> .env
            echo DOCKER_NODE_REPO=${{ secrets.DOCKER_NODE_REPO }} >> .env
            echo DOCKER_SPRING_REPO=${{ secrets.DOCKER_SPRING_REPO }} >> .env
            echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
            echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
            echo SERVER_URL=${{ secrets.SERVER_URL }} >> .env
            echo CRYPTO_KEY=${{ secrets.CRYPTO_KEY }} >> .env

            docker-compose up -d
            docker image prune -f
